name: 'YAJUU-SOU!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#dcd9cf'
    - '#ffffff'
    - '#e4e2db'
    - '#e9e7e1'
  brandStrength: 1
  lightness: 0.8653346025384963
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
